package de.applegreen.household.web.controller.api;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.Map;

/**
 * Grants general Application Information about health and version
 */
@RestController
@RequestMapping("/info")
public class InformationController {

    /**
     * Version generated by Maven filtering
     */
    @Value("${application-version}")
    private String version;

    /**
     * Healthcheck
     * @return 200, OK when application is up
     */
    @SuppressWarnings("rawtypes")
    @GetMapping("/alive")
    public ResponseEntity alive() {
        return ResponseEntity.ok().build();
    }

    /**
     * Version informatiom
     * @return version information
     */
    @GetMapping("/version")
    public ResponseEntity<Map<String, String>> version() {
        Map<String, String> data = new HashMap<>();
        data.put("version", this.version);
        return ResponseEntity.ok().body(data);
    }
}
