@startuml

title __MODEL's Class Diagram__\n

  namespace de.applegreen.household.model {
    class de.applegreen.household.model.Bill {
        - date : LocalDateTime
        - id : Long
        - month : int
        - payedByAlex : boolean
        - payedbySophie : boolean
        - price : Double
        - priceString : String
        - user : String
        + Bill()
        + getDate()
        + getId()
        + getMonth()
        + getPrice()
        + getPriceString()
        + getUser()
        + isPayedByAlex()
        + isPayedbySophie()
        + setDate()
        + setId()
        + setMonth()
        + setPayedByAlex()
        + setPayedbySophie()
        + setPrice()
        + setPriceString()
        + setUser()
    }
  }
  

  namespace de.applegreen.household.model {
    class de.applegreen.household.model.Closing {
        - bills : Collection<Bill>
        - date : LocalDateTime
        - id : Long
        - month : int
        - probationAlex : Double
        - probationCombined : Double
        - probationSophie : Double
        + Closing()
        + Closing()
        + getBills()
        + getDate()
        + getId()
        + getMonth()
        + getProbationAlex()
        + getProbationCombined()
        + getProbationSophie()
        + setBills()
        + setDate()
        + setId()
        + setMonth()
        + setProbationAlex()
        + setProbationCombined()
        + setProbationSophie()
        + toString()
    }
  }
  

  namespace de.applegreen.household.model {
    class de.applegreen.household.model.GroceryList {
        - createdOn : LocalDateTime
        - current : Boolean
        - done : Boolean
        - id : Long
        - products : List<String>
        + GroceryList()
        + getCreatedOn()
        + getCurrent()
        + getDone()
        + getId()
        + getProducts()
        + setCreatedOn()
        + setCurrent()
        + setDone()
        + setId()
        + setProducts()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
