spring:
  datasource:
    url: jdbc:mysql://localhost:3306/household?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: household
    password: LmypxT1995
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  address: 192.168.0.123
  port: 8080