spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/machine
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  groovy:
    template:
      check-template-location: false
server:
  port: 80

